DROP VIEW IF EXISTS person_event_timeline;
DROP VIEW IF EXISTS active_employees;
DROP TRIGGER IF EXISTS trg_account_updated ON person_accounts;
DROP TRIGGER IF EXISTS trg_employment_updated ON employment_records;
DROP TRIGGER IF EXISTS trg_emergency_updated ON emergency_contacts;
DROP TRIGGER IF EXISTS trg_events_immutable ON status_change_events;
DROP TRIGGER IF EXISTS trg_person_updated ON persons;
DROP TRIGGER IF EXISTS trg_org_updated ON organizations;
DROP FUNCTION IF EXISTS set_updated_at();
DROP FUNCTION IF EXISTS reject_event_mutation();
DROP TABLE IF EXISTS person_accounts;
DROP TABLE IF EXISTS employee_benefits;
DROP TABLE IF EXISTS person_certifications;
DROP TABLE IF EXISTS person_documents;
DROP TABLE IF EXISTS person_languages;
DROP TABLE IF EXISTS person_skills;
DROP TABLE IF EXISTS headcount_snapshots;
DROP TABLE IF EXISTS transfer_records;
DROP TABLE IF EXISTS status_change_events;
DROP TABLE IF EXISTS employment_records;
DROP TABLE IF EXISTS emergency_contacts;
DROP TABLE IF EXISTS persons;
DROP TABLE IF EXISTS organizations;
